"""Download a run's generated code bundle as a ZIP archive.

GET /api/runs/{run_id}/code.zip — packages the latest CODE artifact's files
(preserving their relative paths) plus a generated README that captures the
project description, tech stack, and setup/run instructions, so the user can
unzip and run the project directly.
"""
from __future__ import annotations

import io
import re
import zipfile
from typing import Any

from fastapi import APIRouter, Depends, Response

from app.core.auth import require_api_key
from app.core.errors import NotFoundError
from app.models import ArtifactKind
from app.orchestrator.repository import RunRepository

router = APIRouter(
    prefix="/api/runs",
    tags=["code"],
    dependencies=[Depends(require_api_key)],
)


def _repo() -> RunRepository:
    return RunRepository()


def _slug(name: str, *, default: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9._-]+", "-", (name or "").strip()).strip("-._")
    return cleaned.lower() or default


def _safe_member(path: str) -> str:
    """Normalise a file path so the archive can't escape its own folder."""
    cleaned = str(path or "").replace("\\", "/")
    parts = [seg for seg in cleaned.split("/") if seg not in ("", ".", "..")]
    return "/".join(parts) or "file.txt"


def _readme(bundle: dict[str, Any]) -> str:
    lines: list[str] = [f"# {bundle.get('project_name') or 'Generated project'}", ""]
    if bundle.get("description"):
        lines += [str(bundle["description"]), ""]
    stack = bundle.get("tech_stack") or []
    if stack:
        lines += ["## Tech stack", "", *[f"- {t}" for t in stack], ""]
    if bundle.get("setup_instructions"):
        lines += ["## Setup & run", "", "```", str(bundle["setup_instructions"]), "```", ""]
    steps = bundle.get("next_steps") or []
    if steps:
        lines += ["## Next steps", "", *[f"- {s}" for s in steps], ""]
    lines += ["---", "_Generated by the Agentic SDLC Orchestrator._"]
    return "\n".join(lines)


@router.get("/{run_id}/code.zip")
async def download_code_zip(
    run_id: str, repo: RunRepository = Depends(_repo)
) -> Response:
    run = await repo.get_run(run_id)
    if run is None:
        raise NotFoundError(f"Run '{run_id}' not found")

    artifact = await repo.latest_artifact(run_id, ArtifactKind.CODE)
    if artifact is None:
        raise NotFoundError("This run has not generated any code yet.")

    bundle: dict[str, Any] = artifact.content or {}
    project = _slug(bundle.get("project_name", ""), default=f"run-{run_id[:8]}")
    files = bundle.get("files") or []

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(f"{project}/README.md", _readme(bundle))
        used: set[str] = set()
        for entry in files:
            if not isinstance(entry, dict):
                continue
            member = _safe_member(entry.get("path", ""))
            arc = f"{project}/{member}"
            # Don't clobber the README or duplicate paths.
            if arc in used or member == "README.md":
                arc = f"{project}/_dup{len(used)}_{member}"
            used.add(arc)
            zf.writestr(arc, str(entry.get("content", "")))

    data = buf.getvalue()
    return Response(
        content=data,
        media_type="application/zip",
        headers={
            "Content-Disposition": f'attachment; filename="{project}.zip"',
            "Content-Length": str(len(data)),
        },
    )
